---
abstract: 'Returns your ip address with failsafe mechanism'
author:
  - 'David Farrell <sillymoos@cpan.org>'
build_requires:
  Test::More: '0'
  Test::RequiresInternet: '0.03'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WWW-IP
requires:
  Exporter: '0'
  HTTP::Tiny: '0'
  Try::Tiny: '0'
  WWW::curlmyip: '0'
  WWW::hmaip: '0'
  WWW::ipinfo: '0'
  base: '0'
  perl: '5.008'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/sillymoose/WWW-IP
  repository: https://github.com/sillymoose/WWW-IP.git
version: '0.01'
